<a href="https://colab.research.google.com/github/KuchkorovBoburbek/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([1, 3, 5, 7])
print('numpy_array: ', arr)

arr.shape

numpy_array:  [1 3 5 7]


(4,)

In [3]:
arr2 = np.array([1, 3, 5, 7], [1, 3, 5, 7])
print('numpy_array: ', arr)

arr.shape

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [4]:
# dtype()
import numpy as np
arr1 = np.array([1, 2, 3])
print("arr1.item:", arr1.itemsize)
print("arr1.dtype >", arr1.dtype, arr1.nbytes, "\n")

arr2 = np.array([1, 2, 3], dtype='int32')
print("arr2.item:", arr2.itemsize)
print("arr2.dtype >", arr2.dtype, arr2.nbytes, "\n")

arr3 = np.ones((1000))
print(arr3.nbytes)
arr4 = np.ones((1000), dtype='int32')
print(arr4.nbytes)


arr1.item: 8
arr1.dtype > int64 24 

arr2.item: 4
arr2.dtype > int32 12 

8000
4000


In [8]:

# reshape() shape ni o'zgartirish =>
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)

print("arr2:", arr2)

arr2: [[1 2 3]
 [4 5 6]]


In [9]:
#astype() data typelarni ozgartirib beradi
a = np.array([1, 2, 3, 4, 5, 6])
b = a.astype(float)
print("float:", b)

float: [1. 2. 3. 4. 5. 6.]


In [13]:
#np.zeros(), 0dan iborat array, np.ones() 1 dan tashkiol topgan array
z = np.zeros((2, 3))
o = np.ones((2, 3))
print("zeros:", z)
print("zeros:", o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
zeros: [[1. 1. 1.]
 [1. 1. 1.]]


In [14]:

# ndim dimesion nechi ekanligini aytadi
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.ndim)

1


In [15]:
# arange  malum intervalda raqamlardan tashkil topgan array (test uchun kerak boladi )
arr = np.arange(1, 5)
print(arr)

[1 2 3 4]


In [17]:

# sum() yigindi ,  mean() ortachasini aniqlaydi,   max() arraydagi maksimal ,  min() arraydagi minimal
arr = np.array([12, 2, 3, 7, 5, 7])

print("sum:", arr.sum())
print("mean:", arr.mean())
print("max:", arr.max())
print("min:", arr.min())

sum: 36
mean: 6.0
max: 12
min: 2


In [18]:
# flatten() 2d yoki 3d arrayni 1d ga ozgartiradi

arr = np.array([[12, 2, 3], [1, 2, 5]])
print("flatten:", arr.flatten())

flatten: [12  2  3  1  2  5]


In [20]:

# T - transpose
arr1 = np.array([[12, 2, 3, 4], [1, 2, 5, 8]])
print("arr1.transpose:\n", arr1.T, "\n")

arr2 = np.array([
    [[12, 2, 3, 4], [1, 2, 5, 8]],
    [[17, 5, 2, 4], [8, 7, 5, 3]],
    [[7, 15, 0, 2], [3, 1, 9, 1]],
  ])
print("arr2.transpose:\n", arr2.transpose(1,0,2))

arr1.transpose:
 [[12  1]
 [ 2  2]
 [ 3  5]
 [ 4  8]] 

arr2.transpose:
 [[[12  2  3  4]
  [17  5  2  4]
  [ 7 15  0  2]]

 [[ 1  2  5  8]
  [ 8  7  5  3]
  [ 3  1  9  1]]]


In [21]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 0], [5, 7]])

# linier kopaytirish
multip1 = arr1 @ arr2
print("multip1:", multip1, "\n")

# dot function
multip2 = np.dot(arr1, arr2)
print("multip2:", multip2, "\n")

# dot method
multip3 = arr1.dot(arr2)
print("multip3:", multip3, "\n")

# haqiqiy kopaytirish emas!
multip4 = arr1 * arr2
print("multip4:", multip4)

multip1: [[12 14]
 [26 28]] 

multip2: [[12 14]
 [26 28]] 

multip3: [[12 14]
 [26 28]] 

multip4: [[ 2  0]
 [15 28]]
